all::
	sudo pwd
	cp -rf TestPlanTool.sh /usr/local/bin/TestPlanTool.sh
	chmod a+x /usr/local/bin/TestPlanTool.sh
	mkdir /usr/local/bin/testplanToolCode/
	cp -rf testplanToolCode/getTestPlan.lua /usr/local/bin/testplanToolCode/getTestPlan.lua
	cp -rf testplanToolCode/ruler.lua /usr/local/bin/testplanToolCode/ruler.lua
	echo "Install"
clean::
	rm -rf /usr/local/bin/TestPlanTool.sh
	rm -rf /usr/local/bin/testplanToolCode/

