#!/bin/bash
caffeinate &
./lua ./log_combine.lua
ps | grep -e 'caffeinate' | grep -m 1 -v 'grep' | awk '{print $1}' | xargs kill
osascript -e 'tell application "Terminal" to close first window' & exit